name: harshu

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 3 * *"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: harshkumar
        run: echo "hello from harshit"

      - name: second step
        run: echo "ye bhi automatically chalega"


